<?php

require __DIR__ . '/../vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ . '/..');
$dotenv->load();

define('DB_HOST', $_ENV['DB_HOST']);
define('DB_PORT', $_ENV['DB_PORT']);
define('DB_USER', $_ENV['DB_USER']);
define('DB_PASSWORD', $_ENV['DB_PASSWORD']);
define('DB_NAME', $_ENV['DB_NAME']);

define('GOOGLE_CLIENT_ID', $_ENV['GOOGLE_CLIENT_ID']);
define('GOOGLE_CLIENT_SECRET', $_ENV['GOOGLE_CLIENT_SECRET']);

define('BASE_URL', $_ENV['BASE_URL']);
define('OAUTH2_CALLBACK', $_ENV['OAUTH2_CALLBACK']);

define('MEDIA_STORE_API_KEY', $_ENV['MEDIA_STORE_API_KEY']);
define('MEDIA_STORE_NAME', $_ENV['MEDIA_STORE_NAME']);
define('MEDIA_STORE_SECRET', $_ENV['MEDIA_STORE_SECRET']);

define('EMAIL', $_ENV['EMAIL']);

define('REDIS_HOST', $_ENV['REDIS_HOST']);
define('REDIS_PORT', $_ENV['REDIS_PORT']);
define('REDIS_PASSWORD', $_ENV['REDIS_PASSWORD']);
define('REDIS_HASH_KEY', $_ENV['REDIS_HASH_KEY']);
define('REDIS_HASH_ALGO', $_ENV['REDIS_HASH_ALGO']);

define('RES_PASS_SESS_LIFETIME', $_ENV['RES_PASS_SESS_LIFETIME']);
define('RES_PASSWORD_PREFIX', $_ENV['RES_PASSWORD_PREFIX']);


define('EMAIL_SERVICE_HOST', $_ENV['EMAIL_SERVICE_HOST']);
define('EMAIL_SERVICE_PORT', $_ENV['EMAIL_SERVICE_PORT']);
define('EMAIL_SERVICE_SENDER', $_ENV['EMAIL_SERVICE_SENDER']);
define('EMAIL_SERVICE_PASSWORD', $_ENV['EMAIL_SERVICE_PASSWORD']);

define('VERIFICATION_CODE_HASH_KEY', $_ENV['VERIFICATION_CODE_HASH_KEY']);
define('VERIFICATION_CODE_EXPIRY_LEN', $_ENV['VERIFICATION_CODE_EXPIRY_LEN']); // 15 minutes
define('VERIFICATION_CODE_LENGTH', 12);
define('VERIFICATION_CODE_HASH_ALGO', $_ENV['VERIFICATION_CODE_HASH_ALGO']);

?>